### ISSUE TITLE
F4DConverter not work

### ISSUE THREAD

**Issue by yoyomule** [Gaia3D/F4DConverter#1]
Hello, I am testing the conversion function f4dconverter. But nothing is happening while running through cmd. The command I type is:
F:\F4DConverter>F4DConverter.exe -inputFolder F:/input/case.ifc -outFolder F:/output/ -indexing y -log F:/log.txt

![image](https://user-images.githubusercontent.com/10000818/33002413-12d44366-cdef-11e7-919b-2ea396db6b7d.png)

**Comment by shire75** [comment]
'-inputFolder' is for a full path to a folder where .ifc files are, not for any full path to a file.
And, all full path must end without slash or reverse-slash(/ or \).

So, your command line has to be changed into following.

F4DConverter.exe -inputFolder F:\input -outputFolder F:\output -indexing y -log F:\log.txt

**Comment by yoyomule** [comment]
thanks，it‘s ok.
