### ISSUE TITLE
Invalid Arguments - F4DConverter.exe

### ISSUE THREAD

**Issue by iyush1993** [Gaia3D/F4DConverter#1]
I was trying to get started with mago3djs and I followed every step specified in ReadMe. But when it came to converting the file, I got a problem.

When I try to run F4DConverter.exe with the arguments specified in the ReadMe, I get Invalid Arguments error. I changed the argument's value according to my setup but still, it did not work.

**Comment by shire75** [comment]
Please leave your command line you passed to the converter.

**Comment by iyush1993** [comment]
Hey @shire75,
It is similar to wre75 hat is in [ReadMe](https://github.com/Gaia3D/mago3djs#5-data-conversion).
```
F4DConverter.exe -inputFolder E:\mago\f4d\input -outputFolder E:\mago\f4d\first -log E:\mago\f4d\input/log.txt -indexing y
```

**Comment by shire75** [comment]
The prefix, which indicates that a string in a command line is a 'key arguments', has been changed from '-' to '#'.

So, your command line should be changed to

F4DConverter.exe #inputFolder E:\mago\f4d\input #outputFolder E:\mago\f4d\first #log E:\mago\f4d\input/log.txt #indexing y

Sorry for wrong information. We will fix the ReadMe.md

**Comment by iyush1993** [comment]
Hey @shire75 No worries.
The Readme for mago3djs has - but the Readme for F4DConverter is #.

Thank you for the quick response.

**Comment by iyush1993** [comment]
I replaced the prefix, still have same issue.

**Comment by shire75** [comment]
Please leave us a screen capture of your console and the contents of 'E:\mago\f4d\input/log.txt' if created.

**Comment by iyush1993** [comment]
I got it to work now. I just realized that #meshType was mandatory. I was following other documentation and somehow missed that sentence.
Apologies.
