### ISSUE TITLE
F4DConverter 실행 오류

### ISSUE THREAD

**Issue by uyeonH** [Gaia3D/F4DConverter#6]
안녕하세요.

F4DConverter를 설치하고 실행하는 과정에서 오류가 생겨 문의드립니다.
No Argument. 메세지까지 잘 뜨는 것을 확인했습니다.

그런데 F4DConverter #inputFolder ~ 명령어를 실행하면,

[ 현재 PC에서는 이 앱을 실행할 수 없습니다.
PC 버전을 찾으려면 소프트웨어 게시자에게 문의하세요 ] 
라는 메세지가 뜨고,

콘솔창에는 엑세스가 거부되었다고 뜹니다.

**Comment by uyeonH** [comment]
F4DConverter.exe 파일이 있는 곳으로 이동하여 실행했더니 잘 됩니다.

**Comment by JungHam** [comment]
@uyeonH 안녕하세요, 우리 제품에 관심을 가져주셔서 감사합니다. 간혹 관리자모드로 진입하면 실행되는 경우도 있으니 참고 부탁드립니다. 좋은 하루되세요!

**Comment by uyeonH** [comment]
답변 정말 감사드립니다.

한 가지 더 여쭤보고싶은 것이 있습니다.

workshop의 final 자료를 실행시켜보고 있습니다.

![mago](https://user-images.githubusercontent.com/50202274/74298024-eff7aa80-4d8b-11ea-97c6-bb9c17bc3a7a.PNG)


그런데 다음과 같이 웹을 띄우고 버튼을 눌러도 지도상에 Label이나 Bounding Box가 표시되지 않습니다.

그래서 workshop-policy.json 파일의 "geo_cesium_ion_token":"키 값" 을입력해보았는데도
실행이 되지 않습니다.

또, 연속된 위치 값을 지도상에 표시할 수 있는 API가 있을까요?


감사합니다.

**Comment by JungHam** [comment]
@uyeonH f12를 눌러 에러메세지가 어떻게 뜨는지 캡쳐 가능하실까요? 그리고 "geo_cesium_ion_token"은 cesium ion에서 제공하는 terrain을 사용할 때 발급받은 유료 키를 입력하는 옵션이라 상관이 없습니다. 

연속된 위치 값을 지도상에 표시할 수 있는 API라 함은, point같은 형태로 POI를 출력하시고 싶으신 것인가요?

**Comment by uyeonH** [comment]
1. 네, 에러메세지입니다.
![error](https://user-images.githubusercontent.com/50202274/74305982-a23b6c00-4da4-11ea-92ee-af6b3e7a3527.PNG)

2. 네, 맞습니다!

**Comment by JungHam** [comment]
에러메세지를 보니 object index file을 찾지 못해서 에러가 난 듯 싶습니다. 위치를 확인해 주세요. 
2번 기능에 대한 API는 현재로서는 없지만 3월 말에 릴리즈가 될 예정입니다.

**Comment by uyeonH** [comment]
디렉터리 경로를 다음과 같이 했는데 계속 오류가 뜹니다.
**루트디렉터리(workshop)/f4d/dae/...**
**루트디렉터리(workshop)/f4d/las/...**
확인 부탁드려 될까요?

 
![캡처](https://user-images.githubusercontent.com/50202274/74314288-880b8900-4db8-11ea-8fc9-7df0e574133d.PNG)

감사합니다.

**Comment by JungHam** [comment]
workshop 폴더 내에 objectIndexFile.ihe가 있는가요? workshop폴더 스샷 찍어주세요.

**Comment by uyeonH** [comment]
![123](https://user-images.githubusercontent.com/50202274/74316759-809aae80-4dbd-11ea-80ab-dff219505f50.PNG)

C:\workshop\f4d\las\F4D_Tile_+001_+002_+000

이런식으로 되어있고 las와 dae 폴더는 같은 위치에 있습니다!

**Comment by JungHam** [comment]
objectIndexFile.ihe파일을 workshop디렉토리 바로 아래에 넣으셔야 동작합니다. 그렇게 한번 해보시겠어요?

**Comment by uyeonH** [comment]
las와 dae 파일에 각각 objectIndexFile.ihe가 있는데 둘 중 하나만 넣으면 될까요?

![workshop](https://user-images.githubusercontent.com/50202274/74317830-6c57b100-4dbf-11ea-8a42-fe202e7f43b7.PNG)

다음과 같이 넣었는데 같은 오류가 뜹니다

**Comment by JungHam** [comment]
아 일단 저 위치가 아니에요. 제가 좀 헷갈린 부분이 있었습니다. 죄송합니다. 아예 stage7까지 따라오면 어떻게 되는지를 압축해놓은 mago3d-final을 올려놓았으니 구글 드라이브를 다시 한번 참고해 주시겠어요?

**Comment by uyeonH** [comment]
네, 감사드립니다. 다시 해보겠습니다!

그리고 혹시 어제 말씀드렸던 POI 표시를 **drawInsertIssueImageAPI**를 활용해서 가능할까요?

**Comment by JungHam** [comment]
그 기능은 아직 개발 중에 있는 기능으로, 3월 후에 테스트 완료되어 사용가능하십니다. final다운로드받고 잘 실행되는가요?

**Comment by uyeonH** [comment]
새로 업데이트된 파일로 실행해 보았지만 같은 오류가 뜨고있습니다 ㅜ-ㅜ

사실 필요한 기능이 drawInsertIssueImageAPI이고, 
API를 활용하는 방법을 터득하고자 했던 것입니다.

아! 개발 환경을 인텔리제이로 사용하고 있는데, 이건 상관 없을까요?

**Comment by JungHam** [comment]
인텔리제이를 쓰는 것과 관계가 없습니다.
아마 웹서버 위에서 실행시키지 않고 index.html을 바로 실행시켜서 이렇게 되는 것 같습니다...
튜토리얼에 나오는 nginx로 웹서버를 구동하고 있는가요?

문의하신 해당 API는 구현은 되어 있지만, 안정성을 위해 테스트가 조금 더 필요하다고 합니다.
이는 API의 사용 편의성을 위함이니 조금만 더 기다려 주시면 감사하겠습니다.
현재는 Cesium의 point entity에 image를 삽입해서 사용하는 방법으로 대체하고 있습니다.

추가 문의 사항이 있으실 경우에 부담감 느끼지 마시고 문의하세요. 다만 현 issue의 내용이 mago3djs와 관련이 있다 보니 mago3djs의 저장소에서 새로 issue를 열어서 문의해주시면 감사하겠습니다!
